apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: 8xhbx0x0a-java-quarkus
  janus-idp.io/tekton: 8xhbx0x0a-java-quarkus
  backstage.io/kubernetes-id: 8xhbx0x0a-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 8xhbx0x0a-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
